Is the host on the network

diff --git a/basics_0/5-is_the_host_on_the_network b/basics_0/5-is_the_host_on_the_network
--- a/basics_0/5-is_the_host_on_the_network
+++ b/basics_0/5-is_the_host_on_the_network
@@ -1,4 +1,5 @@
 #!/usr/bin/env bash
+# pings an IP address 5 times, if no args were passed, exit 1 (failure)
 if [ "$#" -eq 0 ]
 then
 	echo Usage: 5-is_the_host_on_the_network "$1"
